- name: copy vyos-cli.list
  copy:
    src: vyos-cli.list
    dest: /etc/apt/sources.list.d/vyos-cli.list
    mode: 0644
    owner: root
    group: root

- name: install gpg key
  apt_key:
    url: http://www.ginzado.ne.jp/~m-asama/vyos-cli/vyos-cli.gpg.key
    state: present

- name: update apt cache
  apt:
    update_cache: yes
   
- name: install vyos-cli
  apt:
    name: vyos-cli

- name: execute vyos-cli-setup
  command: vyos-cli-setup

#- name: debug
#  debug:
#    msg: "{{ ansible_default_ipv4.macaddress }}"
#
#- name: execute vyos-cli-ethadd
#  command: "vyos-cli-ethadd {{ ansible_default_ipv4.macaddress }} eth0"

- name: create vyos group
  group:
    name: vyos

- name: create vyos user
  user:
    name: vyos
    shell: /bin/vbash
    groups: 
    - sudo
    - vyos
    - frrvty
    - vyattacfg

- name: reboot machine
  reboot:

- name: disable cloud init
  replace:
    path: /etc/netplan/50-cloud-init.yaml
    regexp: '^[^#](.*)'
    replace: '# \1'
  tags: test


#
#- name: "disable cloud-init's network configuration"
#  copy:
#    src: 99-disable-network-config.cfg
#    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
#    owner: root
#    group: root
#    mode: 0644

- name: execute vyos-cli-ethadd
  command: "vyos-cli-ethadd {{ ansible_default_ipv4.macaddress }} eth0"

